[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd cch-backend && pip install -r requirements.txt"]

[start]
cmd = "cd cch-backend && python seed.py && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
